# Generated by Django 3.2.16 on 2023-01-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('QM', 'QM'), ('QT', 'QT')], default='QT', max_length=2),
        ),
    ]
