# Generated by Django 3.2.16 on 2023-01-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_attempted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='chosen',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='NA', max_length=1),
        ),
    ]
